Repository WuraLab/DNA_backend, pull requests merged in 2020-08, with the labels that each got.

#26 Development : Created the Added Loan Feature
  DNA/settings.py
  DNA/urls.py
  api/admin.py
  api/migrations/0001_initial.py
  api/migrations/0002_auto_20200807_1847.py
  api/migrations/0003_auto_20200709_2304.py
  api/migrations/0004_remove_profile_telephone.py
  api/migrations/0005_profile_phone.py
  api/migrations/0006_auto_20200710_0213.py
  api/migrations/0007_auto_20200710_0241.py
  api/models.py
  api/serializers.py
  api/urls.py
  api/views.py
  requirements.txt
Labels: enhancement

#28 Facebook social authentication
  .vscode/settings.json
  DNA/settings.py
  DNA/urls.py
  api/serializers.py
  api/urls.py
  api/views.py
  requirements.txt
  templates/password_reset_email.html
  templates/password_reset_email.txt
Labels: documentation, enhancement

#27 Custom password recovery
  api/urls.py
  api/views.py
  requirements.txt
Labels: documentation, enhancement

#30 added google social auth
  DNA/settings.py
  DNA/urls.py
  Pipfile
  Pipfile.lock
  Procfile
  api/views.py
  requirements.txt
Labels: documentation, enhancement

#34 update db issues
  api/migrations/0003_auto_20200829_1530.py
  api/migrations/0004_auto_20200829_1531.py
  db.sqlite3
  freeze
Labels: documentation
